//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalExpenseTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccountDetail
    {
        public int Id { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankAccountBankName { get; set; }
        public string BankAccountBranchName { get; set; }
        public string BankAccountNameToDisplay { get; set; }
        public int UserId { get; set; }
    }
}
