//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalExpenseTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string ContactName { get; set; }
        public string ContactDescription { get; set; }
        public string ContactType { get; set; }
        public string ContactTelephoneNumber { get; set; }
        public int UserId { get; set; }
    }
}
