//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalExpenseTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public string EventDate { get; set; }
        public string EventCode { get; set; }
        public string EventName { get; set; }
        public string EventRecurring { get; set; }
        public string EventType { get; set; }
        public string EventCategory { get; set; }
        public string EventAssociatedContact { get; set; }
        public int UserId { get; set; }
    }
}
